[package]
name = "crowbook-localize"
version = "0.0.2"
authors = ["Elisabeth Henry <liz.henry@ouvaton.org>"]
description = "A dirty an ugly library to localize strings in Rust."
readme = "README.md"
keywords = ["localize"]
repository = "https://github.com/lise-henry/crowbook-localize/"
documentation = "https://docs.rs/crowbook-localize"
license = "MPL-2.0"
publish = true

[dependencies]
rustc-serialize = "0.3"
lazy_static = "0.2"
regex = "0.1"
walkdir = "0.1"
