[package]
name = "crowbook-localize"
version = "0.0.3"
authors = ["Elisabeth Henry <liz.henry@ouvaton.org>"]
description = "A library to localize strings, translating them according to runtime options.Using macros."
readme = "README.md"
keywords = ["localize"]
repository = "https://github.com/lise-henry/crowbook-localize/"
documentation = "https://docs.rs/crowbook-localize"
license = "MPL-2.0"
publish = true

[dependencies]
lazy_static = "0.2"
regex = "0.1"
walkdir = "0.1"
